### ISSUE TITLE
Consider adding dynamic page numbers

### ISSUE THREAD

**Issue by ocram** [delight-im/HTML-Sheets-of-Paper#17]
```css
html, body {
	counter-reset: hsop-page-number;
}
.page {
	position: relative;
}
.page::after {
	position: absolute;
	bottom: 10mm;
	left: 0;
	width: 100%;
	display: inline-block;
	counter-increment: hsop-page-number;
	content: "Page " counter(hsop-page-number);
	font-size: 8pt;
	text-align: center;
}
```
